citysciencelab/urban-model-platform

- .dockerignore
- Dockerfile
Include DB migrations in the docker image.
@herzogrh Please review.
> Include migrations in docker image

- src/ump/initializers/db/initialize_keycloak.sql
This adds a initialization sql for the keycloak databse.
Sorry for this messy PR. :see_no_evil:
> Keycloak initalization

- src/ump/api/routes/jobs.py
See title.
@herzogrh Please review.
> Fix jobs authentication filter

- migrations/versions/1.0.0_add_user.py
- migrations/versions/1.0.1_add_process_title_and_name.py
- src/ump/api/job.py
- src/ump/api/process.py
This adds the `process_title` and the `name` to the `Job`.
> Add process_title and name to job

- .env.example
- src/ump/main.py
This makes the protocol of the keycloak server configurable via environment.
> Add KEYCLOAK_PROTOCOL env variable

- Dockerfile.dev
This adds a command to the development docker that runs the DB migrations.
> Run DB migrations 

- migrations/versions/1.0.2_add_ensembles.py
- migrations/versions/1.0.3_extend_ensembles.py
- src/ump/api/ensemble.py
- src/ump/api/job.py
- src/ump/api/process.py
- src/ump/api/processes.py
- src/ump/api/routes/ensembles.py
- src/ump/api/routes/processes.py
- src/ump/main.py
Adds ensembles, ensemble comments and endpoints to read/create them as well as ensemble executions.
Example ensemble:
```json
{
"name": "ensemble",
"description": "ensemble",
"scenario_configs": [{
"process_id": "cut:abm-test-model",
"parameters": {
"agents_per_10000_inhabitants" : {
"from": 1,
"to": 10,
"step": 1
},
"number_iterations" : 12,
"number_steps" : [1, 2, 3]
}
}]
}
```
The parameters can either be specified as single value (`number_iterations`), lists of values (`number_steps`) or as an object specifying a range and a step size (`agents_per_10000_inhabitants`).
Please note that each parameter resulting in multiple values will multiply the number of jobs executed, so if you have e.g. a value like `[true, false]` this will effectively double the number of jobs.
@KaiVolland …
> Add ensembles

- src/ump/api/ensemble.py
- src/ump/api/job.py
- src/ump/api/process.py
- src/ump/api/processes.py
- src/ump/api/providers.py
This adds a constructor for the ensemble and fixes some bugs.
> Adds constructor for ensemble

- migrations/versions/1.0.6_add_postgis_extension.py
- src/ump/api/job.py
- src/ump/geoserver/geoserver.py
> fix: fix geoserver upload

- poetry.lock
- pyproject.toml
- src/ump/api/providers.py
> Reload providers

- migrations/versions/1.0.7_add_version.py
- src/ump/api/job.py
- src/ump/api/process.py
> Add process version

- src/ump/api/routes/ensembles.py
Adds an endpoint to delete jobs from ensembles.
> Delete jobs from ensembles

- poetry.lock
- pyproject.toml
- src/ump/api/routes/ensembles.py
Uses the ema workbench to generate the samples. Available methods are `lhs`, `uniformlhs`, `factorial` and `montecarlo`.
@herzogrh @KaiVolland Please review.
> Use ema workbench

- poetry.lock
- pyproject.toml
- src/ump/__init__.py
- src/ump/api/db_handler.py
- src/ump/api/ensemble.py
- src/ump/api/job.py
- src/ump/api/job_comments.py
- src/ump/api/job_status.py
- src/ump/api/jobs.py
- src/ump/api/keycloak_utils.py
- src/ump/api/process.py
- src/ump/api/processes.py
- src/ump/api/providers.py
- src/ump/api/routes/ensembles.py
- src/ump/api/routes/jobs.py
- src/ump/api/routes/users.py
- src/ump/config.py
- src/ump/errors.py
- src/ump/geoserver/geoserver.py
Also fixes the empty job/user ids bug when fetching jobs.
> fix: fix linting errors

- src/ump/api/keycloak_utils.py
- src/ump/api/routes/ensembles.py
- src/ump/api/routes/jobs.py
- src/ump/api/routes/users.py
This adds interfaces to get the users that have access to a certain entity.
It introduces a user details interface which replaces the user name interface.
The userdetails now include a gravatar url.
> Introduce more interfaces for sharing functionality

- src/ump/api/routes/ensembles.py
- src/ump/api/routes/jobs.py
- ensures only distinct values are fetched
- adds shared entry for the authenticated user
> fix: distinct values

- src/ump/api/job.py
> Remove unneeded logs

- src/ump/api/routes/ensembles.py
This MR adds a route to delete ensembles.
> feat: adds a route to delete an ensemble

- src/ump/api/routes/ensembles.py
> fix: adds missing join

- src/ump/api/routes/ensembles.py
- src/ump/api/routes/jobs.py
Makes sure that ensemble jobs are also shared when sharing ensembles.
> fix: fix sharing of ensembles

- src/ump/api/README.md
- src/ump/api/job.py
- src/ump/api/routes/ensembles.py
- src/ump/geoserver/geoserver.py
Makes the extraction of feature collection from results configurable.
> feat: configure results

- src/ump/main.py
@herzogrh @KaiVolland Please review.
> Use ProxyFix to fix swagger

- src/ump/api/README.md
> feat: add documentation

- src/ump/api/providers.py
> fix: fix reloading of providers.yaml

- poetry.lock
- pyproject.toml
- src/ump/api/job.py
Also adds ipyparallel to fix startup warnings.
> fix: remove guessing result paths

- src/ump/api/job.py
- src/ump/api/jobs.py
> feat: hide anonymous jobs when logged in

- src/ump/api/routes/ensembles.py
> Add jobs to ensembles

- migrations/versions/1.0.11_add_hash.py
- src/ump/api/README.md
- src/ump/api/job.py
- src/ump/api/process.py
- src/ump/main.py
Fixes #20 
@herzogrh @KaiVolland Please review.
> Add caching

- poetry.lock
- pyproject.toml
- src/ump/config.py
- src/ump/main.py
> Cleanup jobs and layers created by anonymous users

- src/ump/api/processes.py
@herzogrh @KaiVolland @FritzHoing Please review.
> Fix matching of model servers with providers

- poetry.lock
- pyproject.toml
- src/ump/api/routes/ensembles.py
@herzogrh @KaiVolland @FritzHoing Please review.
> Use UUID instead of randomly generated names for ensemble jobs

- src/ump/api/keycloak_utils.py
- src/ump/api/routes/users.py
@herzogrh @KaiVolland @FritzHoing Please review.
> feat: remove gravatar url

- src/ump/api/keycloak_utils.py
- src/ump/main.py
This MR reverts some commits temporary.
> Revert commits

- src/ump/api/process.py
This fixes the initial status of a job by setting it to the status of the job on the remote server (Line [311-326](https://github.com/citysciencelab/urban-model-platform/compare/dev...fix-initial-status?expand=1#diff-1ecd55f8ca383f220c81390d5e9d58fcc8c48838aea55ce37e53a60e15f9e9f0R311-R326)).
It also does some formatting.
> Fix initial status of job

- src/ump/api/models/process.py
- src/ump/api/processes.py
- src/ump/main.py
> using setting UMP_KEYCLOAK_CLIENT_ID instead of hard-coded "ump-client"
